- name: print the variable from files
  hosts: web
  vars_files:
  - vars.yaml
  taks:
    - name: print the course
      ansible.builtin.debug:
        msg: "Hi iam learning {{Course}}, Duration is {{Duration}}, Trainer {{Trainer}}"
