- name: loops concept
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix
  