- name: Variables with prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: please enter the course name
  - name: duration
    prompt: please the duration
  - name: Trainer
    prompt: please enter the trainer
  tasks:
  - name: print the course info
    ansible.builtin.debug:
     msg: "Hi iam learning {{course}} duration is {{duration}} trainer is {{trainer}}"
     