- name: variables to print
  hosts: web
  vars:
    Course: Devops
    Duration: 120hrs
    Trainer: Siva
  tasks:
    - name: print the info
      ansible.builtin.debug:
        msg: "Hi iam learning {{Course}} Duration is {{Duration}} Trainer {{Trainer}}"
